### ISSUE TITLE
Add Ngboost

### ISSUE THREAD

**Issue by kmedved** [amitness/toolbox#10]
Ngboost is a gradient boosting library from Andrew Ng's team. The key innovation it adds is that it allows for uncertainty measurements along with point estimates (obviously hugely useful for any number of applications.

https://github.com/stanfordmlgroup/ngboost

(I would submit a pull request, but I am not very comfortable with Git myself; apologies).

**Comment by amitness** [comment]
Thank you @kmedved. I've added it.
