### ISSUE TITLE
Addition of HuggingFace

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [amitness/toolbox#6]
Hi, i'm not sure if it was a conscious decision to leave out HuggingFace. However, since they are currently the best supported and most SOTA library for most NLP related tasks, i strongly recommend adding them. Also, their work on word tokenizers is absolutely amazing, and is also a great addition for non-neural net or non-transformer models.

**Comment by amitness** [comment]
Hi @Baukebrenninkmeijer,

Thanks for suggesting them. Huggingface was already added to the list.

![Screenshot from 2020-04-23 18-41-19](https://user-images.githubusercontent.com/8587189/80102093-0a22e580-8592-11ea-8892-43c614ed0ddb.png)

**Comment by Baukebrenninkmeijer** [comment]
Oh, sorry I missed that! Cool!
